// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockIP(arg1) {
  return window['go']['gui']['App']['BlockIP'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['gui']['App']['CopyToClipboard'](arg1);
}

export function Ctx() {
  return window['go']['gui']['App']['Ctx']();
}

export function ExportAuditLogs(arg1, arg2) {
  return window['go']['gui']['App']['ExportAuditLogs'](arg1, arg2);
}

export function GetActiveSessions() {
  return window['go']['gui']['App']['GetActiveSessions']();
}

export function GetAuditLogs(arg1, arg2) {
  return window['go']['gui']['App']['GetAuditLogs'](arg1, arg2);
}

export function GetBlockedIPs() {
  return window['go']['gui']['App']['GetBlockedIPs']();
}

export function GetCronStatus() {
  return window['go']['gui']['App']['GetCronStatus']();
}

export function GetDashboardHistory() {
  return window['go']['gui']['App']['GetDashboardHistory']();
}

export function GetDashboardStats() {
  return window['go']['gui']['App']['GetDashboardStats']();
}

export function GetPurchaseLimits() {
  return window['go']['gui']['App']['GetPurchaseLimits']();
}

export function GetSecurityConfig() {
  return window['go']['gui']['App']['GetSecurityConfig']();
}

export function GetServerEnvConfig() {
  return window['go']['gui']['App']['GetServerEnvConfig']();
}

export function GetServerStatus() {
  return window['go']['gui']['App']['GetServerStatus']();
}

export function GetStockAlerts() {
  return window['go']['gui']['App']['GetStockAlerts']();
}

export function KillAllSessions() {
  return window['go']['gui']['App']['KillAllSessions']();
}

export function KillSession(arg1) {
  return window['go']['gui']['App']['KillSession'](arg1);
}

export function ReadLogs(arg1) {
  return window['go']['gui']['App']['ReadLogs'](arg1);
}

export function ReloadConfig() {
  return window['go']['gui']['App']['ReloadConfig']();
}

export function RestartServer() {
  return window['go']['gui']['App']['RestartServer']();
}

export function RunCronJob(arg1) {
  return window['go']['gui']['App']['RunCronJob'](arg1);
}

export function SaveAuditLogsToFile(arg1) {
  return window['go']['gui']['App']['SaveAuditLogsToFile'](arg1);
}

export function SaveLogToFile(arg1) {
  return window['go']['gui']['App']['SaveLogToFile'](arg1);
}

export function SetPurchaseLimit(arg1, arg2) {
  return window['go']['gui']['App']['SetPurchaseLimit'](arg1, arg2);
}

export function SetSecurityConfig(arg1) {
  return window['go']['gui']['App']['SetSecurityConfig'](arg1);
}

export function ShutdownServer() {
  return window['go']['gui']['App']['ShutdownServer']();
}

export function UnblockIP(arg1) {
  return window['go']['gui']['App']['UnblockIP'](arg1);
}
