// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {gui} from '../models';
import {cron} from '../models';
import {monitor} from '../models';

export function BlockIP(arg1:string):Promise<string>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function Ctx():Promise<context.Context>;

export function ExportAuditLogs(arg1:number,arg2:number):Promise<string>;

export function GetActiveSessions():Promise<Array<gui.SessionInfo>>;

export function GetAuditLogs(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetBlockedIPs():Promise<Array<gui.BlockedIPInfo>>;

export function GetCronStatus():Promise<Array<cron.JobStatus>>;

export function GetDashboardHistory():Promise<Array<monitor.HistoryPoint>>;

export function GetDashboardStats():Promise<monitor.Stats>;

export function GetPurchaseLimits():Promise<gui.LimitConfig>;

export function GetSecurityConfig():Promise<gui.SecurityConfig>;

export function GetServerEnvConfig():Promise<gui.ServerEnvConfig>;

export function GetServerStatus():Promise<gui.ServerStatus>;

export function GetStockAlerts():Promise<Array<gui.StockAlert>>;

export function KillAllSessions():Promise<string>;

export function KillSession(arg1:number):Promise<string>;

export function ReadLogs(arg1:string):Promise<string>;

export function ReloadConfig():Promise<string>;

export function RestartServer():Promise<string>;

export function RunCronJob(arg1:string):Promise<string>;

export function SaveAuditLogsToFile(arg1:string):Promise<string>;

export function SaveLogToFile(arg1:string):Promise<string>;

export function SetPurchaseLimit(arg1:string,arg2:string):Promise<string>;

export function SetSecurityConfig(arg1:gui.SecurityConfig):Promise<string>;

export function ShutdownServer():Promise<void>;

export function UnblockIP(arg1:string):Promise<string>;
